[application]
name = "zdx"
title = "ZDX"
version = "package.json::version"
organization = "ASPECTRON Inc"

[description]
short = "Desktop Node and Wallet for Zua"
long = """
ZDX is a desktop wallet and a p2p network node instance. This application
allows you to participate in the Zua network by running a local node
instance and offers access to a local wallet, compatible with the web
wallet 
"""

[package]
archive = { include = true }
signatures = ["SHA256"]
build = [
    { NPM = { clean = true } }
]
# wasm = "root/wasm"
resources = "resources/setup"
output = "setup/$PLATFORM-$ARCH"
include = [
    { glob = [
            "bin/*",
            "*.js",
            "resources/**.css",
            "resources/images/*.*",
            "resources/**.ttf",
            "resources/**.woff",
            "resources/**.svg",
            "i18n.*",
            "modules/*",
            "lib/*",
            "node_modules/*",
            "package.json"
        ]},
]

[[action]]
items = [{ copy = { glob = [
        ".templates",
        ".defaults",
        "CHANGELOG.md"
    ], to = "$TARGET", hidden = true}}]

[[dependency]]
name = "zuad"
git = { url = "https://github.com/zuanet/zuad", branch = "master" }
run = [
    { cmd = "go build" },
    { cmd = "go build", cwd = "cmd/genkeypair" },
    { cmd = "go build", cwd = "cmd/zuactl" },
    { cmd = "go build", cwd = "cmd/zuawallet" },
]
copy = [
    { regex = [
        "zuad(.exe)?$",
        "genkeypair(.exe)?$",
        "zuactl(.exe)?$",
        "zuawallet(.exe)?$",
    ], to = "bin/$PLATFORM-$ARCH", flatten = true },
]

[[dependency]]
name = "zua-miner"
platform = ["windows", "linux"]
git = { url = "https://github.com/aspectron/zua-miner", branch = "main" }
run = [{ argv = ["cargo","build","--release","-p","zuacuda"] }]
copy = [
    { regex = [
        "target/release/zuacuda(.so|.dll)$",
        "target/release/zuaopencl(.so|.dll)$",
        "target/release/zua-miner(.exe)?$",
    ], to = "bin/$PLATFORM-$ARCH", flatten = true },
    # { file = "target/release/zua-miner$EXE", to = "bin/$PLATFORM-$ARCH/gpuminer$EXE" },
]

[nwjs]
version = "0.55.0"
ffmpeg = false

[macos-disk-image]
window_caption_height = 60
window_position = [400,100]
window_size = [485,330]
icon_size = 72
application_icon_position = [100,158]
system_applications_folder_position = [385,158]

[windows]
uuid = "c1072045-6d98-44d8-9aa5-e9be6c79bd01"
group = "Zua"
# run_on_startup = "everyone"
run_after_setup = true

[images]
application="logo.png"
macos-application="Icon1024.png"
macos-disk-image="zdx-dmg.png"
innosetup-icon="logo.png"
innosetup-wizard-small="zdx-55x58.bmp"
innosetup-wizard-large="zdx-164x314.bmp"

[languages]
languages = ["english","french"]

[firewall]
application = { direction = "in+out" }
rules = [
    { name = "Zua Node", program = "bin/windows-x64/zuad.exe", direction="in+out" },
    { name = "Zua GPU Miner", program = "bin/windows-x64/gpuminer.exe", direction="out" }
]
